version: '3.5'

services:
  config-service:
    container_name: config-service
    build: config-service
    ports:
      - 8001:8001

  registry:
    container_name: registry
    restart: always
    build: registry
    ports:
      - 8761:8761
    depends_on:
      - config-service


  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - 8989:8989
    depends_on:
      - config-service
      - registry

  account-service:
    restart: on-failure
    container_name: account-service
    build: account-service
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - registry
      - postgres-account

  bill-service:
    restart: on-failure
    container_name: bill-service
    build: bill-service
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - registry
      - postgres-bill

  deposit-service:
    restart: on-failure
    container_name: deposit-service
    build: deposit-service
    ports:
      - 8083:8083
    depends_on:
      - config-service
      - registry
      - postgres-deposit

  notification-service:
    restart: on-failure
    container_name: notification-service
    build: notification-service
    depends_on:
      - config-service
      - registry

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - config-service
      - registry
      - account-service

  postgres-account:
    restart: always
    image: postgres:13
    container_name: postgres-account
    environment:
      POSTGRES_DB: account_service_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d account_service_database"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres-bill:
    restart: always
    image: postgres:13
    container_name: postgres-bill
    environment:
      POSTGRES_DB: bill_service_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bill_service_database"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres-deposit:
    restart: always
    image: postgres:13
    container_name: postgres-deposit
    environment:
      POSTGRES_DB: deposit_service_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5436:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d deposit_service_database" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s